#! /bin/sh

for ARG in $@; do

	echo "#include \"$ARG.hpp\"" >$ARG.cpp
	echo "#include <iostream>" >>$ARG.cpp
	echo "" >>$ARG.cpp
	echo "// CONSTRUCTORS AND DESTRUCTORS-------------------------------------------------" >>$ARG.cpp
	echo "$ARG::$ARG(void) {" >>$ARG.cpp
	echo "    std::cout << \"$ARG default constructor called\" << std::endl;" >>$ARG.cpp
	echo "}" >>$ARG.cpp
	echo "" >>$ARG.cpp
	echo "$ARG::$ARG($ARG const &other) {" >>$ARG.cpp
	echo "    std::cout << \"$ARG copy constructor called\" << std::endl;" >>$ARG.cpp
	echo "    *this = other;" >>$ARG.cpp
	echo "}" >>$ARG.cpp
	echo "" >>$ARG.cpp
	echo "$ARG::~$ARG(void) {" >>$ARG.cpp
	echo "    std::cout << \"$ARG destructor called\" << std::endl;" >>$ARG.cpp
	echo "}" >>$ARG.cpp
	echo "" >>$ARG.cpp
	echo "// OPERATORS--------------------------------------------------------------------" >>$ARG.cpp
	echo "$ARG &$ARG::operator=($ARG const &other) {" >>$ARG.cpp
	echo "    if (this != &other){" >>$ARG.cpp
	echo "        // DO THINGS" >>$ARG.cpp
	echo "    }" >>$ARG.cpp
	echo "    return (*this);" >>$ARG.cpp
	echo "}" >>$ARG.cpp
	echo "" >>$ARG.cpp
	echo "// METHODS AND MEMBER FUNCTIONS-------------------------------------------------" >>$ARG.cpp

	UPPERCASE=$(echo $ARG | tr a-z A-Z)
	echo "#ifndef _${UPPERCASE}_HPP" >$ARG.hpp
	echo "#define _${UPPERCASE}_HPP" >>$ARG.hpp
	echo "" >>$ARG.hpp
	echo "class $ARG {" >>$ARG.hpp
	echo "  public:" >>$ARG.hpp
	echo "    $ARG(void);" >>$ARG.hpp
	echo "    $ARG($ARG const &other);" >>$ARG.hpp
	echo "    ~$ARG(void);" >>$ARG.hpp
	echo "" >>$ARG.hpp
	echo "    $ARG &operator=($ARG const &other);" >>$ARG.hpp
	echo "};" >>$ARG.hpp
	echo "" >>$ARG.hpp
	echo "#endif // !_${UPPERCASE}_HPP" >>$ARG.hpp

done
