= 42 Orthodox Canonical Class Form

A shell script to create classes in the orthodox cannonical class form for the cpp projects at 42 School

== Installation
.Clone the repository
[source, sh]
....
git clone https://github.com/witemirlo/42-Orthodox-Canonical-Class-Form.git $HOME/.orthodox-canonical-class-form
....

.Set permissions
[source, sh]
....
cd $HOME/.orthodox-canonical-class-form
....

[source, sh]
....
chmod +x class
....

.Bash
[source, sh]
....
echo 'export PATH=$PATH:$HOME/.orthodox-canonical-class-form' >> $HOME/.bashrc
....

.Zsh
[source, sh]
....
echo 'export PATH=$PATH:$HOME/.orthodox-canonical-class-form' >> $HOME/.zshrc
....

.Fish
[source, sh]
....
fish_add_path $HOME/.orthodox-canonical-class-form
....

== Usage
[source, sh]
....
class NAME_OF_THE_CLASS
....
This generates a .cpp and a .hpp files with the given NAME_OF_THE_CLASS with a default constructor, a default destructor, a default copy constructor and an assigment operator.

.You can make as many classes as you want just listing them
[source, sh]
....
class NAME1 NAME2 NAME3 NAME4
....
